apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sourabh
namePrefix: sourabh-

resources:
- Deployment.yaml
- Services.yaml

images:
- name: nginx
  newTag: 1.20.0

replicas:
- count: 1
  name: sourabh-nginx-deployment
